# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changeimg.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import windowButton, windowButton_hover
from movablewidget import movableWidget

class Ui_mainFrame(object):
    def setupUi(self, mainFrame):
        mainFrame.setObjectName("mainFrame")
        mainFrame.resize(500, 250)
        mainFrame.setMinimumSize(QtCore.QSize(500, 250))
        self.verticalLayout = QtWidgets.QVBoxLayout(mainFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main = QtWidgets.QFrame(mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.main.setMinimumSize(QtCore.QSize(100, 100))
        self.main.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.main.setFont(font)
        self.main.setStyleSheet("background-color: rgb(255, 230, 153);\n"
"border-radius: 30px;")
        self.main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setObjectName("main")
        self.gridLayout = QtWidgets.QGridLayout(self.main)
        self.gridLayout.setObjectName("gridLayout")
        self.cancel = QtWidgets.QPushButton(self.main)
        self.cancel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 230, 153);\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(197, 197, 197);\n"
"border-radius: 15px;\n"
"}")
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 5, 0, 1, 1)
        self.confirm = QtWidgets.QPushButton(self.main)
        self.confirm.setMinimumSize(QtCore.QSize(0, 30))
        self.confirm.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.confirm.setFont(font)
        self.confirm.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 230, 153);\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(197, 197, 197);\n"
"border-radius: 15px;\n"
"}")
        self.confirm.setObjectName("confirm")
        self.gridLayout.addWidget(self.confirm, 5, 1, 1, 1)
        self.notifi = QtWidgets.QLabel(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notifi.sizePolicy().hasHeightForWidth())
        self.notifi.setSizePolicy(sizePolicy)
        self.notifi.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.notifi.setFont(font)
        self.notifi.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius: 0px;")
        self.notifi.setAlignment(QtCore.Qt.AlignCenter)
        self.notifi.setObjectName("notifi")
        self.gridLayout.addWidget(self.notifi, 1, 0, 1, 2)
        self.titleFrame = movableWidget(mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleFrame.sizePolicy().hasHeightForWidth())
        self.titleFrame.setSizePolicy(sizePolicy)
        self.titleFrame.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-right-radius: 20px;\n"
"border-top-left-radius: 20px;")
        self.titleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.titleFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(99999, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.close = QtWidgets.QPushButton(self.titleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close.sizePolicy().hasHeightForWidth())
        self.close.setSizePolicy(sizePolicy)
        self.close.setMinimumSize(QtCore.QSize(20, 20))
        self.close.setMaximumSize(QtCore.QSize(20, 20))
        self.close.setStyleSheet("border-image: url(:/source/close.PNG)")
        self.close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/source/close.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close.setIcon(icon)
        self.close.setObjectName("close")
        self.horizontalLayout_2.addWidget(self.close)
        self.gridLayout.addWidget(self.titleFrame, 0, 0, 1, 2)
        self.filePath = QtWidgets.QLineEdit(self.main)
        self.filePath.setMinimumSize(QtCore.QSize(0, 35))
        self.filePath.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.filePath.setFont(font)
        self.filePath.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius: 0px;")
        self.filePath.setObjectName("filePath")
        self.gridLayout.addWidget(self.filePath, 2, 0, 1, 2)
        self.verticalLayout.addWidget(self.main)

        self.retranslateUi(mainFrame)
        QtCore.QMetaObject.connectSlotsByName(mainFrame)

    def retranslateUi(self, mainFrame):
        _translate = QtCore.QCoreApplication.translate
        mainFrame.setWindowTitle(_translate("mainFrame", "Form"))
        self.cancel.setText(_translate("mainFrame", "취소"))
        self.confirm.setText(_translate("mainFrame", "확인"))
        self.notifi.setText(_translate("mainFrame", "바꿀 프로필 사진 경로를\n"
"아래 입력칸에 적어주세요"))
