# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'schedule_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from movablewidget import movableWidget
import windowButton, windowButton_hover

class Ui_mainFrame(object):
    def setupUi(self, mainFrame):
        mainFrame.setObjectName("mainFrame")
        mainFrame.resize(283, 515)
        mainFrame.setMinimumSize(QtCore.QSize(250, 500))
        mainFrame.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(mainFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main = QtWidgets.QFrame(mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.main.setMinimumSize(QtCore.QSize(100, 100))
        self.main.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.main.setFont(font)
        self.main.setStyleSheet("background-color: rgb(255, 230, 153);\n"
"border-radius: 30px;")
        self.main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setObjectName("main")
        self.gridLayout = QtWidgets.QGridLayout(self.main)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = movableWidget(mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-right-radius: 20px;\n"
"border-top-left-radius: 20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(99999, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.close = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close.sizePolicy().hasHeightForWidth())
        self.close.setSizePolicy(sizePolicy)
        self.close.setMinimumSize(QtCore.QSize(20, 20))
        self.close.setMaximumSize(QtCore.QSize(20, 20))
        self.close.setStyleSheet("QPushButton{\n"
"border-image: url(:/source/close.PNG);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/source_hover/close_hover.png);\n"
"}")
        self.close.setText("")
        self.close.setIconSize(QtCore.QSize(0, 0))
        self.close.setObjectName("close")
        self.horizontalLayout_2.addWidget(self.close)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)
        self.scheduleTitle = QtWidgets.QLabel(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scheduleTitle.sizePolicy().hasHeightForWidth())
        self.scheduleTitle.setSizePolicy(sizePolicy)
        self.scheduleTitle.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.scheduleTitle.setFont(font)
        self.scheduleTitle.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius: 0px;")
        self.scheduleTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.scheduleTitle.setObjectName("scheduleTitle")
        self.gridLayout.addWidget(self.scheduleTitle, 1, 0, 1, 2)
        self.confirm = QtWidgets.QPushButton(self.main)
        self.confirm.setMinimumSize(QtCore.QSize(0, 30))
        self.confirm.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.confirm.setFont(font)
        self.confirm.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 230, 153);\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(197, 197, 197);\n"
"border-radius: 15px;\n"
"}")
        self.confirm.setObjectName("confirm")
        self.gridLayout.addWidget(self.confirm, 5, 0, 1, 2)
        self.schedule = QtWidgets.QTableWidget(self.main)
        self.schedule.setGridStyle(QtCore.Qt.SolidLine)
        self.schedule.setRowCount(0)
        self.schedule.setColumnCount(2)
        self.schedule.setHorizontalHeaderLabels(['날짜', '일정'])
        self.schedule.setObjectName("schedule")
        self.gridLayout.addWidget(self.schedule, 2, 0, 1, 2)
        self.add = QtWidgets.QPushButton(self.main)
        self.add.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add.setFont(font)
        self.add.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 230, 153);\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(197, 197, 197);\n"
"border-radius: 15px;\n"
"}")
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 3, 0, 2, 2)
        self.verticalLayout.addWidget(self.main)

        self.retranslateUi(mainFrame)
        QtCore.QMetaObject.connectSlotsByName(mainFrame)

    def retranslateUi(self, mainFrame):
        _translate = QtCore.QCoreApplication.translate
        mainFrame.setWindowTitle(_translate("mainFrame", "Form"))
        self.scheduleTitle.setText(_translate("mainFrame", "현재일정"))
        self.confirm.setText(_translate("mainFrame", "확인"))
        self.add.setText(_translate("mainFrame", "칸 추가"))
